enableLegacyBowPosition = true
enableLegacyRodPosition = true
enableLegacySneakAnimation = true
enableSwordBlockingAnimation = true
enableSwordBlockingAnimationShield = true
enableLegacyPlayerList = true
